### ISSUE TITLE
Too strict bounds on hspec

### ISSUE THREAD

**Issue by sternenseemann** [klapaucius/vector-hashtables#11]
From my testing, the test suite also builds fine with `hspec == 2.8.*`.

**Comment by andreasabel** [comment]
Fixed this on Hackage by relaxing to `<2.11`: https://hackage.haskell.org/package/vector-hashtables-0.1.1.1/revisions/

**Comment by swamp-agr** [comment]
Should be fixed in #14. Please expect release on Hackage soon.

**Comment by swamp-agr** [comment]
Please find minor release on Hackage: https://hackage.haskell.org/package/vector-hashtables-0.1.1.2

**Comment by andreasabel** [comment]
@swamp-agr: Few know this, but if you just want to fix bounds of dependencies in the `.cabal` file, you can make a revision on Hackage, at https://hackage.haskell.org/package/vector-hashtables/maintain .  
I did that to `0.1.1.1` in my role as Hackage Trustee.

**Comment by swamp-agr** [comment]
@andreasabel: I know that it is possible to achieve via Hackage, thank you for pointing it out. I personally don't like that it will introduce discrepancy between GitHub and Hackage. Sometimes it leads to a certain obscure issues where you are spending time looking why specific build plan changed and etc. Moreover, page https://hackage.haskell.org/package/vector-hashtables-0.1.1.1/revisions/ is not indexed by search engines so you have to keep in mind that you need to look for a clue on package page on Hackage. So that's why I consider revision feature as a workaround but not a permanent fix.

**Comment by andreasabel** [comment]
That's fine, it is your choice.  Note however that it _is_ possible to also track the revisions on github, so that github is always in sync with hackage.  
One can upload revisions with the https://github.com/hackage-trustees/hackage-cli tool, and then commit and tag them in the git repo. (You might have to to this on a release branch if you already have code changes in the master branch.)

See an example here: https://github.com/haskell-hvr/brotli-streams/tags

NB. You can also download revisions with `hackage-cli pull-cabal`.
